name: 'AI Issue Assessment Commenter'
description: Generate an AI comment on issues based on a prompt file and labels.

branding:
  icon: 'message-square'
  color: orange

inputs:
  token:
    description: The token to use
    required: true
  ai_review_label:
    description: The label applied to the issue to trigger AI review
    required: true
  issue_number:
    description: The issue number to comment on
    required: true
  issue_body:
    description: The body of the issue to comment on
    required: true
  prompts_directory:
    description: The path to the prompts directory
    required: true
  labels_to_prompts_mapping:
    description: "A mapping of labels to prompt files, separated by '|'. Format: 'label1,prompt1.prompt.yml|label2,prompt2.prompt.yml'"
    required: true
  model:
    description: The model to use for AI generation
    required: false
  endpoint:
    description: The endpoint to use
    required: false
  max_tokens:
    description: The maximum number of tokens to generate
    required: false
  repo_name:
    description: The name of the repository
    required: false
  owner:
    description: The owner of the repository
    required: false
  assessment_regex_pattern:
    description: 'Regex pattern for capturing the assessment line in the AI response used for creating the label to add to the issue. Default: "/^###.*[aA]ssessment:/"'
    required: false
    default: '^###.*[aA]ssessment:\\s*(.+)$'
  assessment_regex_flags:
    description: 'Regex flags for the assessment regex pattern. e.g.: "i" for case-insensitive matching.'
    required: false
    default: ''
runs:
  using: node20
  main: dist/index.js
