name: 'AI Issue Assessment Commenter'
description: Generate an AI comment on issues based on a prompt file and labels.

inputs:
  token:
    description: The token to use
    required: true
  ai_review_label:
    description: The label applied to the issue to trigger AI review
    required: true
  prompts_directory:
    description: The path to the prompts directory
    required: true
  labels_to_prompts_mapping:
    description: "A mapping of labels to prompt files, separated by '|'. Format: 'label1,prompt1.prompt.yml|label2,prompt2.prompt.yml'"
    required: true
  model:
    description: The model to use for AI generation
    required: false
  endpoint:
    description: The endpoint to use
    required: false
  max_tokens:
    description: The maximum number of tokens to generate
    required: false
runs:
  using: node20
  main: dist/index.js
